services:
  mongo:
    image: mongo:7.0
    container_name: efact-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: documents_db
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: efact-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
