application:
  name: ms-documentos

server:
  port: 8081

spring:
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_BD:documento_bd}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

app:
  key:
    private: ${PRIVATE_KEY:Lz^&RQukkUsBBH!9RihP}